### ISSUE TITLE
Why different log format

### ISSUE THREAD

**Issue by PFadel** [Optum/kong-splunk-log#3]
Hello,

I just wanted to ask, since kong already has a log format in it's [other plugins](https://docs.konghq.com/hub/kong-inc/http-log/) why does this one has a different format ? Could we log the same info ?

**Comment by jeremyjpj0916** [comment]
@PFadel Hello, our logging plugin was built for our needs to be compact and small as well as minimizing any PHI data with only the most relevant metadata due to Splunks charge-back model based on consumption/file sizes. If you would like to leverage Kong's default format which has more info by default  feel free to fork the repo and tweak it to your needs. All you would need to do is take Kong's github repo basic.lua and drop it into our plugin overwriting our basic.lua and be sure to add our splunk variables back into the file:
```
local splunkHost= os.getenv("SPLUNK_HOST")
host=splunkHost,
```
